matrix:
  include:
    - language: c
      services:
        - docker
      before_install:
        - docker pull ubuntu:16.04
      script:
        - docker run -v $PWD:/root -w /root ubuntu:16.04 /bin/sh -c "sed -i -e 's/# deb-src/deb-src/' /etc/apt/sources.list && apt-get -qq update && apt-get -y build-dep melt && apt-get -y install qt5-default locales && ./configure --prefix=/usr --enable-gpl --enable-gpl3 --enable-lumas && make -j && make install && cd src/tests && qmake tests.pro && make -j && echo de_DE.UTF-8 UTF-8 >> /etc/locale.gen && locale-gen && for test in \$(find . -type f -name 'test_*' -executable); do \$test; done"
        - docker build -t mltframework/melt:latest .
      after_success:
        - test "$TRAVIS_REPO_SLUG" = "mltframework/mlt" -a $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "master" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test "$TRAVIS_REPO_SLUG" = "mltframework/mlt" -a $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "master" && docker push mltframework/melt
    - language: python
      python: 3.7
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      before_install: pip install flake8
      script:
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
